### ISSUE TITLE
NovidBootReceiver does nothing

### ISSUE THREAD

**Issue by michaelroland** [novid20org/novid20-android-sdk#11]
NovidBootReceiver listens, but does nothing besides logging a debug message. Was this meant to start discovery upon boot?

**Comment by myfknoll** [comment]
From my point of of view, the BootReveiver will be triggered after system boot. 
When the BootReceiver is called, the Application is also created, and we can therefore start detection and re-configure scheduling

**Comment by michaelroland** [comment]
So the app is expected to instantiate the SDK implementation when the Application context is created and the boot receiver just makes sure that the app is loaded (an application context is created) upon boot-up?

**Comment by myfknoll** [comment]
Yes exactly, we added some comments inside the code

**Comment by christxph** [comment]
Closing this because the class purpose [has been documented](https://github.com/novid20org/novid20-android-sdk/blob/master/novid-sdk/src/main/java/org/novid20/sdk/NovidBootReceiver.kt#L17).
