### ISSUE TITLE
Phone number normalization inhibits area codes that coincidentally match the country code

### ISSUE THREAD

**Issue by michaelroland** [novid20org/novid20-android-sdk#7]
The [phone number normalization](https://github.com/novid20org/novid20-android-sdk/blob/6532f6f93bcdb28c5b50acc1ebf88126902d72a7/novid-sdk/src/main/java/org/novid20/sdk/utils/FormattingUtils.kt#L15) inhibits the use of phone numbers where the first digits of the area code match the country code. While this might not be problematic for Austrian mobile phone numbers, this may not hold true for other countries and also prevents certain Austrian landline phone numbers (the whole Lavanttal?) to be used.

For instance, the phone number 04350 123456 or +43 4350 123456(valid area code for Bad St. Leonhard), would be parsed into 50123456.

**Comment by christxph** [comment]
Thanks a lot for reporting this issue, we have fixed it in the next iteration of the SDK.
